In [8]:
import os 
import numpy as np 

In [2]:
import pandas as pd 

In [3]:
pwd

'c:\\Users\\ambek\\OneDrive - UvA\\Course_related\\period5\\DL2\\clone\\FACT_AI\\code\\counterfactual_generative_networks-main\\mnists'

In [16]:
#open pandas file 
df = pd.read_csv('Imgs_CF_new/noise.csv')

In [19]:
#convert all values to float values 
df2 = df.astype(float)

In [20]:
df2

Unnamed: 0     0_0  -2.858484  -0.027844513  0.9346912  -0.27608654  \
0            NaN     1.0   1.149741      0.762755   1.072855     0.535812   
1            NaN     2.0   0.545240     -0.678804  -0.606159    -0.710242   
2            NaN     3.0  -0.509416     -1.321556   0.138047    -0.153945   
3            NaN     4.0   0.147483     -0.227092   0.169482    -0.322083   
4            NaN     5.0   0.336339      1.863688   0.484251    -1.299087   
...          ...     ...        ...           ...        ...          ...   
9994         NaN  9995.0  -0.146039     -1.493226   1.153572    -0.581481   
9995         NaN  9996.0   0.491096      1.913994  -0.108406    -0.674899   
9996         NaN  9997.0   0.993183     -0.603910   1.183048     0.654168   
9997         NaN  9998.0  -0.983832     -0.244386  -1.086757     1.344375   
9998         NaN  9999.0   0.572767     -1.040478   0.947508     0.185371   

      -0.06689211  1.6750911  -0.4615493  -0.39592206  ...  -1.5852572  \
0       -1.118594   1.068048    0.200911     1.185346  ...   -1.585257   
1       -0.708428   1.124922    0.467613    -1.195333  ...   -1.585257   
2       -0.946203   1.125739   -0.173078    -0.316963  ...   -1.585257   
3        0.402625   1.195301    0.210835     0.945275  ...   -1.585257   
4       -0.016484  -1.310916   -2.275313     0.380626  ...   -1.585257   
...           ...        ...         ...          ...  ...         ...   
9994    -2.209159  -0.494292   -0.228259    -0.800362  ...    0.414068   
9995    -1.040277   0.975072   -0.967527     0.508849  ...    0.414068   
9996    -1.590391   1.262236   -0.194813     0.207859  ...    0.414068   
9997    -1.697423   0.686046    1.175458     0.155891  ...    0.414068   
9998    -1.952386  -1.256429   -1.105199    -0.154686  ...    0.414068   

      -1.7834536  -0.051291756  -0.6816404  0.8744239  0.58359104  \
0      -1.783454     -0.051292   -0.681640   0.874424    0.583591   
1      -1.783454     -0.051292   -0.681640   0.874424    0.583591   
2      -1.783454     -0.051292   -0.681640   0.874424    0.583591   
3      -1.783454     -0.051292   -0.681640   0.874424    0.583591   
4      -1.783454     -0.051292   -0.681640   0.874424    0.583591   
...          ...           ...         ...        ...         ...   
9994    0.858226      0.409555   -1.264317   1.114408   -1.575914   
9995    0.858226      0.409555   -1.264317   1.114408   -1.575914   
9996    0.858226      0.409555   -1.264317   1.114408   -1.575914   
9997    0.858226      0.409555   -1.264317   1.114408   -1.575914   
9998    0.858226      0.409555   -1.264317   1.114408   -1.575914   

      0.053670704  -2.3345566  0.59820837  -1.4054946  
0        0.053671   -2.334557    0.598208   -1.405495  
1        0.053671   -2.334557    0.598208   -1.405495  
2        0.053671   -2.334557    0.598208   -1.405495  
3        0.053671   -2.334557    0.598208   -1.405495  
4        0.053671   -2.334557    0.598208   -1.405495  
...           ...         ...         ...         ...  
9994     0.248652   -0.409426   -0.862603    0.053838  
9995     0.248652   -0.409426   -0.862603    0.053838  
9996     0.248652   -0.409426   -0.862603    0.053838  
9997     0.248652   -0.409426   -0.862603    0.053838  
9998     0.248652   -0.409426   -0.862603    0.053838  

[9999 rows x 44 columns]

In [21]:
#convert to numpy array
df_np = df.to_numpy()


In [10]:
#check for nan values 

In [14]:
import numpy as np

In [22]:
#save as numpy array 
np.save('Imgs_CF_new/labels_new_mod.npy', df_np)

In [32]:
#load numpy array
a = np.load('Imgs_CF_new/labels_new_mod.npy', allow_pickle=True)

In [33]:
a.shape

(9999, 44)

In [29]:
#delete first column of numpy array
a2 = np.delete(a, 0, 1)

In [31]:
a2.shape

(9999, 43)

In [38]:
#convert array to float values 
a2_float = a2.astype(float)

In [55]:
a2[1][1:]

array([0.5452398, -0.67880416, -0.6061595, -0.71024245, -0.7084277,
       1.124922, 0.46761262, -1.1953328, -1.3596965, -1.557822, 0.7691858,
       0.34648025, -0.5768383, 0.0024177942, -0.188176, 0.43112367,
       -0.71166795, -0.17540345, -1.0523267, -0.5527117, -0.36135104,
       0.025524369, 0.51898277, 1.1915153, -1.2920074, -1.2920176,
       1.2575321, -1.3161461, -1.5635189, 0.5383857, 1.1354606,
       0.82197404, -1.5852572, -1.7834536, -0.051291756, -0.6816404,
       0.8744239, 0.58359104, 0.053670704, -2.3345566, 0.59820837,
       -1.4054946], dtype=object)

In [54]:
a2[1][1:].astype(float)

array([ 0.5452398 , -0.67880416, -0.6061595 , -0.71024245, -0.7084277 ,
        1.124922  ,  0.46761262, -1.1953328 , -1.3596965 , -1.557822  ,
        0.7691858 ,  0.34648025, -0.5768383 ,  0.00241779, -0.188176  ,
        0.43112367, -0.71166795, -0.17540345, -1.0523267 , -0.5527117 ,
       -0.36135104,  0.02552437,  0.51898277,  1.1915153 , -1.2920074 ,
       -1.2920176 ,  1.2575321 , -1.3161461 , -1.5635189 ,  0.5383857 ,
        1.1354606 ,  0.82197404, -1.5852572 , -1.7834536 , -0.05129176,
       -0.6816404 ,  0.8744239 ,  0.58359104,  0.0536707 , -2.3345566 ,
        0.59820837, -1.4054946 ])

In [67]:
tmp = a2

In [68]:
#convert 2nd element to last element of 1st row to float values
tmp[1][1:] = a2[1][1:].astype(float)

In [73]:
a2[1][1:].astype(float)

array([ 0.5452398 , -0.67880416, -0.6061595 , -0.71024245, -0.7084277 ,
        1.124922  ,  0.46761262, -1.1953328 , -1.3596965 , -1.557822  ,
        0.7691858 ,  0.34648025, -0.5768383 ,  0.00241779, -0.188176  ,
        0.43112367, -0.71166795, -0.17540345, -1.0523267 , -0.5527117 ,
       -0.36135104,  0.02552437,  0.51898277,  1.1915153 , -1.2920074 ,
       -1.2920176 ,  1.2575321 , -1.3161461 , -1.5635189 ,  0.5383857 ,
        1.1354606 ,  0.82197404, -1.5852572 , -1.7834536 , -0.05129176,
       -0.6816404 ,  0.8744239 ,  0.58359104,  0.0536707 , -2.3345566 ,
        0.59820837, -1.4054946 ])

In [71]:
tmp[1][1:].astype(float)

array([ 0.5452398 , -0.67880416, -0.6061595 , -0.71024245, -0.7084277 ,
        1.124922  ,  0.46761262, -1.1953328 , -1.3596965 , -1.557822  ,
        0.7691858 ,  0.34648025, -0.5768383 ,  0.00241779, -0.188176  ,
        0.43112367, -0.71166795, -0.17540345, -1.0523267 , -0.5527117 ,
       -0.36135104,  0.02552437,  0.51898277,  1.1915153 , -1.2920074 ,
       -1.2920176 ,  1.2575321 , -1.3161461 , -1.5635189 ,  0.5383857 ,
        1.1354606 ,  0.82197404, -1.5852572 , -1.7834536 , -0.05129176,
       -0.6816404 ,  0.8744239 ,  0.58359104,  0.0536707 , -2.3345566 ,
        0.59820837, -1.4054946 ])

In [42]:
#check data type of array
a2_float.dtype

dtype('float64')

In [46]:
a2_float

array([[ 1.0000000e+00,  1.1497406e+00,  7.6275456e-01, ...,
        -2.3345566e+00,  5.9820837e-01, -1.4054946e+00],
       [ 2.0000000e+00,  5.4523980e-01, -6.7880416e-01, ...,
        -2.3345566e+00,  5.9820837e-01, -1.4054946e+00],
       [ 3.0000000e+00, -5.0941640e-01, -1.3215562e+00, ...,
        -2.3345566e+00,  5.9820837e-01, -1.4054946e+00],
       ...,
       [ 9.9970000e+03,  9.9318320e-01, -6.0390955e-01, ...,
        -4.0942600e-01, -8.6260265e-01,  5.3838074e-02],
       [ 9.9980000e+03, -9.8383220e-01, -2.4438570e-01, ...,
        -4.0942600e-01, -8.6260265e-01,  5.3838074e-02],
       [ 9.9990000e+03,  5.7276670e-01, -1.0404782e+00, ...,
        -4.0942600e-01, -8.6260265e-01,  5.3838074e-02]])

In [43]:
#save a2 as np array
np.save('Imgs_CF_new/labels_new_mod2.npy', a2)

In [74]:
b= np.load('Imgs_CF_new/labels_new_mod2.npy', allow_pickle=True)

In [78]:
noise_value = b[55][1:].astype(float)

In [77]:
b.shape

(9999, 43)

In [79]:
noise_value

array([-0.8346291 , -1.7599514 , -0.28297928, -0.04009812, -1.8653744 ,
        0.37303084, -0.3910288 ,  1.2146894 , -0.97224313,  1.4402109 ,
        0.32763284,  2.4421573 ,  0.0108912 , -0.45130992,  3.7960012 ,
       -0.5146202 ,  1.6760054 , -0.10422662, -1.2378911 ,  1.4541829 ,
       -0.7450485 , -0.10800173,  0.37603506,  0.27155867,  0.6228057 ,
       -0.00591595, -0.4724406 , -0.59705234,  0.90858626,  0.8033383 ,
        0.7532596 ,  1.483014  , -1.5852572 , -1.7834536 , -0.05129176,
       -0.6816404 ,  0.8744239 ,  0.58359104,  0.0536707 , -2.3345566 ,
        0.59820837, -1.4054946 ])

In [76]:
noise_value

array([-0.5094164 , -1.3215562 ,  0.13804679, -0.15394469, -0.9462031 ,
        1.1257392 , -0.1730785 , -0.3169631 , -1.5615587 , -1.1214024 ,
       -0.41098267, -0.27436903, -0.74978155, -0.25403225,  1.0173554 ,
        1.4561068 , -0.75558215,  0.39349002,  0.6097995 , -0.02803077,
        0.4770395 , -0.57160014,  0.64288217,  0.36308196, -0.93172014,
       -0.53154945, -0.5060561 ,  0.17357412, -0.72803414, -0.85338   ,
        0.19986755, -1.5486925 , -1.5852572 , -1.7834536 , -0.05129176,
       -0.6816404 ,  0.8744239 ,  0.58359104,  0.0536707 , -2.3345566 ,
        0.59820837, -1.4054946 ])